name: algobait
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  http: ^1.4.0
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  url_launcher: ^6.3.2
  dots_indicator: ^3.0.0
  lottie: ^3.1.0
  smooth_page_indicator: ^1.1.0
  confetti: ^0.7.0
  share_plus: ^9.0.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  image: ^4.1.7
  flutter_animate: ^4.5.0
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  crypto: ^3.0.3
  pointycastle: ^3.9.1
  flutter_inappwebview: ^6.1.5
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutterfire_cli: ^1.3.1

dependency_overrides:
  web: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
