// File generated by Cascade to fix Firebase configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- IMPORTANT ---
  // The configurations for Web and Windows below might be outdated.
  // Please register Web and Windows apps in your 'algobait-official'
  // Firebase project and update them here for full functionality.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWs1eklOx1yDOCMliWekm7KdxyKE8AJro', // NOTE: This apiKey might be from the old project. Please verify in Firebase console.
    appId: '1:905788187928:web:15f6479a18e19282a82a6d',
    messagingSenderId: '905788187928',
    projectId: 'algobait-official',
    authDomain: 'algobait-official.firebaseapp.com',
    storageBucket: 'algobait-official.firebasestorage.app',
  );

  // Android options from your `google-services.json`
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV2C9AiDg-NDIcGs1eST47feAG1qFAJbY',
    appId: '1:905788187928:android:16325d9e59cdd0cfa82a6d',
    messagingSenderId: '905788187928',
    projectId: 'algobait-official',
    storageBucket: 'algobait-official.firebasestorage.app',
  );

  // iOS options from your `GoogleService-Info.plist`
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVNg2I5c4l93483jsIrFJyclMXzqJSwJc',
    appId: '1:905788187928:ios:010b86c2569f383fa82a6d',
    messagingSenderId: '905788187928',
    projectId: 'algobait-official',
    storageBucket: 'algobait-official.firebasestorage.app',
    iosBundleId: 'com.example.algobait',
  );

  // macOS options (uses the same as iOS)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVNg2I5c4l93483jsIrFJyclMXzqJSwJc',
    appId: '1:905788187928:ios:010b86c2569f383fa82a6d',
    messagingSenderId: '905788187928',
    projectId: 'algobait-official',
    storageBucket: 'algobait-official.firebasestorage.app',
    iosBundleId: 'com.example.algobait',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWs1eklOx1yDOCMliWekm7KdxyKE8AJro', // NOTE: This apiKey might be from the old project. Please verify in Firebase console.
    appId: '1:905788187928:web:15f6479a18e19282a82a6d', // Using web App ID as a fallback for Windows
    messagingSenderId: '905788187928',
    projectId: 'algobait-official',
    authDomain: 'algobait-official.firebaseapp.com',
    storageBucket: 'algobait-official.firebasestorage.app',
  );
}
