// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWs1eklOx1yDOCMliWekm7KdxyKE8AJro',
    appId: '1:232565114032:web:8894e2303cd9f94164a775',
    messagingSenderId: '232565114032',
    projectId: 'algobait-beta25',
    authDomain: 'algobait-beta25.firebaseapp.com',
    storageBucket: 'algobait-beta25.firebasestorage.app',
    measurementId: 'G-LW25Q2QTQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlajqLkTb7D8YQPYbZ0vyLWq5um0pGb3g',
    appId: '1:232565114032:android:55ae7f268458e13164a775',
    messagingSenderId: '232565114032',
    projectId: 'algobait-beta25',
    storageBucket: 'algobait-beta25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0ASdj_v5sPzJLXYYZMfzgED5Dh4qlCg',
    appId: '1:232565114032:ios:94209a264055ab1a64a775',
    messagingSenderId: '232565114032',
    projectId: 'algobait-beta25',
    storageBucket: 'algobait-beta25.firebasestorage.app',
    iosBundleId: 'com.example.algobait',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf0ASdj_v5sPzJLXYYZMfzgED5Dh4qlCg',
    appId: '1:232565114032:ios:94209a264055ab1a64a775',
    messagingSenderId: '232565114032',
    projectId: 'algobait-beta25',
    storageBucket: 'algobait-beta25.firebasestorage.app',
    iosBundleId: 'com.example.algobait',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWs1eklOx1yDOCMliWekm7KdxyKE8AJro',
    appId: '1:232565114032:web:e5b378296a459d2164a775',
    messagingSenderId: '232565114032',
    projectId: 'algobait-beta25',
    authDomain: 'algobait-beta25.firebaseapp.com',
    storageBucket: 'algobait-beta25.firebasestorage.app',
    measurementId: 'G-R7GJZ6P4D6',
  );
}
